#!/bin/sh

SERVERCMD="${SERVERCMD:-unison}"
REMOTESERVER="${REMOTESERVER}"

export UNISON=/unison
export UNISONLOCALHOSTNAME=${UNISONLOCALHOSTNAME:-container}
unison -servercmd "${SERVERCMD}" -batch /target "${REMOTESERVER}"
